### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by bekirbakar** [oswjk/portablepython#4]
Is there or will be python package for linux and macOS. I checked your releases but there are only for windows.

If you suggest a way i can do and pull as request.

Thanks in advance.

**Comment by oskaritimperi** [comment]
I'm not aware of similar package for Linux or macOS. I'm not intending to support anything else than Windows at this point. My reasoning is that it's a pain to install different versions of Python on Windows (using the official installers it's hard to install 3.5.1 and 3.5.4 at the same time if you happen to need them). On Linux and macOS it's easy to build new versions and put them wherever.
